apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  namespace: go-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: sayemiit/auth-service:sha-59b0c43
          ports:
            - containerPort: 10000   # <-- fixed port
          env:
            - name: MONGO_URI
              value: "mongodb://admin:sayem@mongo-service:27017"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: go-todo-secrets
                  key: jwt-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /api/v1/auth/me
              port: 10000          # <-- fixed port
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/v1/auth/me
              port: 10000          # <-- fixed port
            initialDelaySeconds: 15
            periodSeconds: 15
