apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-persistent-storage-mongo-0
  namespace: go-todo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: gp2
  volumeMode: Filesystem
